---
driver:
  name: docker

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: debian-7.9

suites:
  - name: default
    run_list:
      - recipe[simianarmy::default]
    attributes:
