name 'simianarmy'
maintainer 'Chef Software Inc.'
maintainer_email 'rhass@chef.io'
license 'apache2'
description 'Installs/Configures simianarmy'
long_description 'Installs/Configures simianarmy'
version '0.1.0'

depends 'ark'
depends 'apt'
depends 'git'
depends 'gradle'
depends 'java'
depends 'poise-python'
